g++ -g SpatialGrid.cpp -c -I /home/lucas/Headers/SFML-2.5.1/include/
g++ -g SpatialGrid.cpp -c -I /home/lucas/Headers/SFML-2.5.1/include/
g++ -g main.cpp -c -I /home/lucas/Headers/SFML-2.5.1/include/
g++ -g main.o SpatialGrid.o -o test -L /home/lucas/Headers/SFML-2.5.1/lib/ -lsfml-system -lsfml-window -lsfml-graphics -Wl,-rpath=/home/lucas/Headers/SFML-2.5.1/lib/
